extends:
  - airbnb-base
  - plugin:prettier/recommended
env:
  browser: true

overrides:
  - files:
      - projects/job-listings/**/*.{js,jsx}
      - projects/github-jobs/**/*.{js,jsx}
    parser: babel-eslint
    extends:
      - airbnb
      - airbnb/hooks
      - plugin:jest/recommended
      - plugin:jest/style
      - plugin:prettier/recommended
      - prettier/react
    env:
      browser: true
      node: true
      jest: true
    plugins:
      - simple-import-sort
    rules:
      simple-import-sort/imports: error
      simple-import-sort/exports: error
      sort-imports: off
      import/order: off
      react/require-default-props:
        - error
        - ignoreFunctionalComponents: true
      jsx-a11y/label-has-associated-control:
        - error
        - assert: either

  - files:
      - projects/github-jobs/**/*.{js,jsx}
    plugins:
      - jss
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies:
            - projects/github-jobs/config/webpack.*.js
      react/react-in-jsx-scope: off
      jss/sort-jss-keys: error

  - files:
      - projects/github-jobs/config/**/*.js
    rules:
      simple-import-sort/imports: off
      import/order:
        - error
        - newlines-between: always

settings:
  import/resolver:
    webpack:
      config: './projects/github-jobs/config/webpack.common.js'
