url: "https://alex-k1m.github.io"
baseurl: "/html-templates"
title: "HTML Templates"
collections:
  fm-challenges:
    output: true
    permalink: /:title
defaults:
  - scope:
      path: ""
      type: "fm-challenges"
    values:
      layout: "fm-challenge"
exclude: [makefile, package.json, package-lock.json]