name: Deploy all

on:
  - workflow_dispatch

jobs:
  deploy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Lerna
        uses: actions/cache@v2
        id: lerna-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn boot

      - name: Test
        run: |
          yarn run lint
          yarn run test

      - name: Build
        run: |
          yarn run build:all
          mkdir build
          ls -F projects | grep "\/$" | xargs -I % cp -r projects/%public build/% 2>/dev/null

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
